### ISSUE TITLE
好像代理不了，帮我看看啥原因？

### ISSUE THREAD

**Issue by etimes2008** [shunf4/proxychains-windows#12]
v2rayn sock5 port 10808

[ProxyList]
socks5 localhost 10808

run:
PS F:\proxychains_0.6.8_win32_x64> F:\proxychains_0.6.8_win32_x64\proxychains_win32_x64.exe -f F:\proxychains_0.6.8_win32_x64\proxychains.conf D:\msys64\mingw64\bin\curl.exe ip.sb
[PID25924] [I] 2020/11/13 19:01:51 Ws2_32.dll connect(476 127.0.0.1:1080 16) DIRECT
curl: (7) Failed to connect to 127.0.0.1 port 1080: Connection refused
[I] 2020/11/13 19:01:54 All Windows descendant process exited.
[I] 2020/11/13 19:01:54 Master exiting
PS F:\proxychains_0.6.8_win32_x64>

why connect(476 127.0.0.1:1080 ???

**Comment by shunf4** [comment]
你的 `curl` 自己连接了代理服务器 `127.0.0.1:1080`，按 `proxychains` 的规则应该走直连，然后这个端口拒绝连接。检查下环境变量，看是不是配置了 `ALL_PROXY` 这种会让 `curl` 走代理的变量
