### ISSUE TITLE
GenericRXHT-WK!14B2C7F1FACD Trojan detected in proxychains_hook_x86.dll

### ISSUE THREAD

**Issue by huornlmj** [shunf4/proxychains-windows#19]
The file proxychains_hook_x86.dll is reported as containing GenericRXHT-WK!14B2C7F1FACD Trojan by McAfee Endpoint Security.

**Comment by shunf4** [comment]
I won't fix this.

If you have security concerns, check the code, compile it for yourself, add it into whitelist and use it.
