### ISSUE TITLE
Update README.md with real (Win 10) %s% please.

### ISSUE THREAD

**Issue by bs27975** [shunf4/proxychains-windows#25]
Could https://github.com/shunf4/proxychains-windows/blob/master/README.md please be updated to add / change:

(SYSCONFDIR)/proxychains.conf (Cygwin) or (User roaming dir)\Proxychains\proxychains.conf (Win32)
/etc/proxychains.conf (Cygwin) or (Global programdata dir)\Proxychains\proxychains.conf (Win32)

to

(SYSCONFDIR)/proxychains.conf (Cygwin) or %APPDATA%\Proxychains\proxychains.conf (Win32)
/etc/proxychains.conf (Cygwin) or %ProgramData%\Proxychains\proxychains.conf (Win32)

if appropriate, or a wiki article created to list what "(User roaming dir)" and "(Global programdata dir)" are? These are non-standard names, and taking guesswork out of things is always good.

**Comment by shunf4** [comment]
Proxychains needs to be compatible with Windows XP SP3, where `%ProgramData%` does not exist.

I've updated README.md to clarify where default configuration file paths are located on both platforms.
