### ISSUE TITLE
.conf - include file directorive?

### ISSUE THREAD

**Issue by bs27975** [shunf4/proxychains-windows#28]
Is there an include file directive possible for the proxychains.conf file?

If not, could there be? And in either case, could a wiki article be created to so explain, please?

Further, could a 'variable' be permitted to be used in such a line, to represent the directory within which the .exe is located?

Then one could put a

fileinclude %exedir%\proxychains.conf

type of line in a default location, so .exe and .conf can be kept together.

Further, one could also create different lists of proxies, perhaps programmatically, then have the resulting list of proxies auto included in the .conf file by virtue of the 'fileinclude' directive.

**Comment by shunf4** [comment]
I would prefer what you said in #26 - check for conf file in the same directory of proxychains.exe.

Implementing an include directive makes things a little bit more complicated, and possibly brings problems, e.g. circular inclusion.

Resolving variables complicates things, too.

However, you are welcome to fork the repo and implement these features for your own convenience.
