### ISSUE TITLE
For more than one proxy it doesn't work

### ISSUE THREAD

**Issue by Mahdi321** [shunf4/proxychains-windows#3]
My primary proxy is psiphon, second one is a private proxy
[ProxyList]
socks5 localhost	1080
socks5 54.38.195.161 56299
>proxychains_win32_x64.exe "C:\Program Files (x86)\Google\Chrome\Application\chrome.exe"
.
.
.
[PID15372] [I] 2020/04/27 08:47:24 <> localhost:1080
[PID15372] [W] 2020/04/27 08:47:25 Socks5 data format invalid: server disallows this connection
[PID15372] [W] 2020/04/27 08:47:25 Ws2_32.dll connect(2440 224.8.107.83:443 16) -> www.google.com:443 PROXY ret: -1, wsa last error: Access is denied.(5)
[PID15372] [W] 2020/04/27 08:47:25 recv() error: An existing connection was forcibly closed by the remote host.(10054)
[PID15372] [W] 2020/04/27 08:47:25 Ws2_32.dll connect(2468 [2001:4860:4860::8888]:53 28) PROXY ret: -1, wsa last error: An existing connection was forcibly closed by the remote host.(10054)
[PID15372] [I] 2020/04/27 08:47:25 <> localhost:1080
[PID15372] [W] 2020/04/27 08:47:25 Socks5 data format invalid: server disallows this connection
[PID15372] [W] 2020/04/27 08:47:25 Ws2_32.dll connect(2476 224.28.48.248:443 16) -> api.infura.io:443 PROXY ret: -1, wsa last error: Access is denied.(5)

**Comment by shunf4** [comment]
It looks like `localhost:1080` rejects your connection(STATUS does not equal to 0) in [response packet](https://en.wikipedia.org/wiki/SOCKS#SOCKS5) i.e. reply packet.

Please check if `localhost:1080` works well as a SOCKS5 server, and if you can, give a tcpdump of a working proxy connection attempt.

**Comment by Mahdi321** [comment]
It appears problem is that when the proxy is localhost it works, but when it is remote it doesn't

**Comment by shunf4** [comment]
@Mahdi321 You mean
```
socks5 localhost 1080
```
works, but
```
socks5 localhost 1080
socks5 54.38.195.161 56299
```
doesn't?

**Comment by shunf4** [comment]
To make it clear when you want to request SOCKS5 server `localhost:1080` to connect to `54.38.195.161:56299`, it refuses it.

**Comment by Mahdi321** [comment]
yes, the combination causes fast refuse
Also any remote proxy (without chaining) cause timeout

**Comment by shunf4** [comment]
@Mahdi321 You should ensure the remote proxy is available before using it. I have tried some proxies on http://spys.one/en/socks-proxy-list/ from different places, and most of the connection attempts resulted in a timeout. Try 174.70.241.14:24392, that should be usable.

**Comment by Mahdi321** [comment]
This proxy currently is not a working one (not suitable for testing)

**Comment by Mahdi321** [comment]
that one is not a working proxy. But I tested with this one 91.238.137.108:8975 (another spyone proxy) which works in Firefox proxy setting and bot in proxychains.exe (timeout)

**Comment by shunf4** [comment]
@Mahdi321 At least I can access this proxy at present. There may be differences among regions from which the connection begins.
![](https://user-images.githubusercontent.com/20991618/80369001-25f2f800-88c0-11ea-9c78-93718a0a009b.png)

So yes, pick a proxy accessible by the previous proxy server in chain, and things should work.

**Comment by shunf4** [comment]
Please run `curl -x socks5h://91.238.137.108:8975 ip.sb` to check if it really works.

**Comment by Mahdi321** [comment]
Give me a private contact way I will send data to access my PC

**Comment by shunf4** [comment]
@Mahdi321 From currently known information it is most probable that psiphon(`localhost:1080`) is not allowing connection to these anonymous proxies, or these proxies have problem of availability. Until you provide more proof that proxychains is mainly to blame for this issue, I would suggest troubleshooting it on your own.

**Comment by shunf4** [comment]
@Mahdi321 `91.238.137.108:8975` is available now, and the proxy chain `localhost:1079 <> 91.238.137.108:8975 <> ip.sb` works normally on my side.

**Comment by Mahdi321** [comment]
About Psiphon maybe you are right now I tested chaining another proxy. `curl' run without problem. But running firefox
```
[PID42956]`` [W] 2020/04/28 06:26:07 Ws2_32.dll connect(4664 224.192.76.219:443 16) -> incoming.telemetry.mozilla.org:443 PROXY ret: -1, wsa last error: This operation returned because the timeout period expired.(1460)
```
