### ISSUE TITLE
incompatible with the requested protocol was used when using with browsers (with remote proxies)

### ISSUE THREAD

**Issue by Mahdi321** [shunf4/proxychains-windows#4]
When using curl there is no problem:
![untitled](https://user-images.githubusercontent.com/27496531/80390081-f4573e00-8879-11ea-9fdd-6cd75be29bee.png)

But with browser like chrome timeout happens:
![Untitled2](https://user-images.githubusercontent.com/27496531/80390110-ff11d300-8879-11ea-9cc0-73c792c42769.png)
the proxy work correctly when used in chrome proxy add-ons or system proxy

**Comment by shunf4** [comment]
This is expected. When the first proxy server is not accessible by a IPv6 address, proxychains could not proxify connections to IPv6 addresses (see configuration options `first_tunnel_uses_ipv4` and `first_tunnel_uses_ipv6`). Try visiting some sites with IPv4 addresses and check everything behaves normally.
