### ISSUE TITLE
Possibility of providing Application Command Line Arguments 

### ISSUE THREAD

**Issue by abhishekmani12** [shunf4/proxychains-windows#55]
Hello, I was wondering if it is possible to specify command line arguments for an app when trying to launch it with proxychains.

Eg:
`proxychains "some\path\to\app.exe -option1 -option2 ....."`

It tried modifying `args_and_config.c` but couldn't work it out. Could you please shed some light on this?

**Comment by shunf4** [comment]
Quote each

**Comment by abhishekmani12** [comment]
Thanks, I'm able to pass it.
