### ISSUE TITLE
Make local proxy that forwards traffic through proxy chain

### ISSUE THREAD

**Issue by t1m013y** [shunf4/proxychains-windows#56]
How to make proxychains not proxying all traffic from executable through proxy, but listening local port (for example, 127.0.0.1:9000) and forwarding it through proxy chain (for example, SOCKS5 127.0.0.1:9000 -> SOCKS5 \<addr1\>:\<port1\> -> HTTPS \<addr2\>:\<port2\> -> internet)?

**Comment by shunf4** [comment]
This is totally beyond proxychains' purpose, but the Chinese are masters of this kind of work. Some projects:

- https://www.v2fly.org/en_US/
- https://github.com/ginuerzh/gost
- https://github.com/SagerNet/sing-box

**Comment by t1m013y** [comment]
Thanks! V2ray looks like what I need.
