### ISSUE TITLE
运行不了，报错

### ISSUE THREAD

**Issue by littleheary** [shunf4/proxychains-windows#6]
λ proxychains curl google.com
[W] 2020/05/10 21:11:37 SetThreadContext() Failed: 句柄无效。(6)
[E] 2020/05/10 21:11:37 Injecting WINPID 13308 Error: 句柄无效。(6)
[I] 2020/05/10 21:11:37 No child process registered. Injection might not have succeeded.
curl: (56) Recv failure: Connection was reset
[I] 2020/05/10 21:11:37 Master exiting

**Comment by shunf4** [comment]
请尝试以下操作：
- 关闭所有安全软件再试一次
- 不要使用 cmder/ConEmu，直接（用 ConHost）运行 cmd.exe 再试一次
- 把 curl 换成一些其他命令行程序再试一次

看哪些操作可以解决问题。

如果没有解决问题，请提供以下信息：
- Windows 的版本、是 x64 还是 x86
- Proxychains.exe 的版本、平台、是 32-bit 还是 64-bit（用 `proxychains.exe -h` 查看）
- `curl -V` 的输出（需要版本、位置、平台等信息）
- 使用 Debug 版本的 Proxychains，运行 `proxychains -lD curl google.com` 的输出（日志信息）

**Comment by shunf4** [comment]
[ConEmu 同样用 hook 阻止了其他程序进行 `SetThreadContext()`](https://github.com/Maximus5/ConEmu/blob/9629fa82c8a4c817f3b6faa2161a0a9eec9285c4/src/ConEmuHk/hkProcess.cpp#L497)，这导致了 ConEmu 和 Proxychains 不可能兼容。请直接使用 ConHost（cmd.exe）或者切换到其他不使用大量 Hook 的终端模拟器。

**Comment by chenjr15** [comment]
确实是ConEmu的问题
